#theme: jekyll-theme-cayman
theme: jekyll-theme-hacker
# webpage title
title: Bi0T1N's GitHub Page
# general information
description: Some (hopefully) useful information
# provide a download URL?
show_downloads: false